package rep

const (
	SelectUserByNickname           = "select nickname, fullname, about, email from users where nickname=$1 limit 1;"
	SelectUserByEmailOrNickname    = "select nickname, fullname, about, email from users where nickname=$1 or email=$2 limit 2;"
	SelectForumBySlug              = "select title, \"user\", slug, posts, threads from forum where slug=$1 limit 1;"
	InsertInForum                  = "insert into forum(slug, \"user\", title) values ($1, $2, $3);"
	SelectThread                   = "select id, title, author, forum, message, votes, slug, created from threads where slug = $1 limit 1;" // TODO: 0_o
	SelectThreadSlug               = "select id, title, author, forum, message, votes, slug, created from threads where slug = $1 limit 1;"
	GetUsersOfForumDescNotNilSince = "select nickname, fullname, about, email from users_forum where slug=$1 and nickname < '%s' order by nickname desc limit nullif($2, 0)"
	GetUsersOfForumDescSinceNil    = "select nickname, fullname, about, email from users_forum where slug=$1 order by nickname desc limit nullif($2, 0)"
	GetUsersOfForumDescNil         = "select nickname, fullname, about, email from users_forum where slug=$1 and nickname > '%s' order by nickname limit nullif($2, 0)"
	GetThreadsSinceDescNotNil      = "select id, title, author, forum, message, votes, slug, created from threads where forum=$1 and created <= $2 order by created desc limit $3;"
	GetThreadsSinceDescNil         = "select id, title, author, forum, message, votes, slug, created from threads where forum=$1 and created >= $2 order by created asc limit $3;"
	GetThreadsDescNotNil           = "select id, title, author, forum, message, votes, slug, created from threads where forum=$1 order by created desc limit $2;"
	GetThreadsDescNil              = "select id, title, author, forum, message, votes, slug, created from threads where forum=$1 order by created asc limit $2;"
	SelectPostById                 = "select parent, author, message, isedited, forum, thread, created from posts where id = $1;"
	SelectThreadId                 = "select id, title, author, forum, message, votes, slug, created from threads where id = $1 LIMIT 1;"
	UpdatePostMessage              = "update posts set message=coalesce(nullif($1, ''), message), isedited = case when $1 = '' or message = $1 then isedited else true end where id=$2 returning id, parent, author, message, isedited, forum, thread, created, path"
	ClearAll                       = "truncate table users, forum, threads, posts, votes, users_forum CASCADE;"
	SelectCountUsers               = "select count(*) from users;"
	SelectCountForum               = "select count(*) from forum;"
	SelectCountThreads             = "select count(*) from threads;"
	SelectCountPosts               = "select count(*) from posts;"
	InsertThread                   = "insert into threads (author, message, title, created, forum, slug, votes) values ($1, $2, $3, $4, $5, $6, $7) returning id"
	UpdateThread                   = "update threads set title=coalesce(nullif($1, ''), title), message=coalesce(nullif($2, ''), message) where %s returning id, title, author, forum, message, votes, slug, created"
	SelectPostSinceDescNotNil      = "select id, parent, author, message, isedited, forum, thread, created from posts where thread=$1 order by id desc limit $2;"
	SelectPostSinceDescNil         = "select id, parent, author, message, isedited, forum, thread, created from posts where thread=$1 order by id limit $2;"
	SelectPostDescNotNil           = "select id, parent, author, message, isedited, forum, thread, created from posts where thread=$1 and id < $2 order by id desc limit $3;"
	SelectPostDescNil              = "select id, parent, author, message, isedited, forum, thread, created from posts where thread=$1 and id > $2 order by id limit $3;"
	SelectThreadShort              = "select slug, author from threads where slug = $1;"
	SelectSlugFromForum            = "select slug from forum where slug = $1;"
	InsertIntoPosts                = "insert into posts(author, created, forum, message, parent, thread) values"
	SelectTreeLimitSinceNil        = "select id, parent, author, message, isedited, forum, thread, created from posts where thread = $1 order by path, id desc"
	SelectTreeLimitSinceDescNil    = "select id, parent, author, message, isedited, forum, thread, created from posts where thread = $1 order by path, id asc"
	SelectTreeSinceNil             = "select id, parent, author, message, isedited, forum, thread, created from posts where thread = $1 order by path desc, id desc limit $2"
	SelectTreeSinceDescNil         = "select id, parent, author, message, isedited, forum, thread, created from posts where thread = $1 order by path, id asc limit $2"
	SelectTreeNotNil               = "select posts.id, posts.author, posts.created, posts.forum, posts.isedited, posts.message, posts.parent, posts.thread from posts join posts parent on parent.id = $2 where posts.path < parent.path and posts.thread = $1 order by posts.path desc, posts.id desc limit $3"
	SelectTree                     = "select posts.id, posts.author, posts.created, posts.forum, posts.isedited, posts.message, posts.parent, posts.thread from posts join posts parent on parent.id = $2 where posts.path > parent.path and posts.thread = $1 order by posts.path asc, posts.id asc limit $3"
	SelectTreeSinceNilDesc         = "select posts.id, posts.author, posts.created, posts.forum, posts.isedited, posts.message, posts.parent, posts.thread from posts join posts parent on parent.id = $2 where posts.path < parent.path and posts.thread = $1 order by posts.path desc, posts.id desc"
	SelectTreeSinceNilDescNil      = "select posts.id, posts.author, posts.created, posts.forum, posts.isedited, posts.message, posts.parent, posts.thread from posts join posts parent on parent.id = $2 where posts.path > parent.path and posts.thread = $1 order by posts.path asc, posts.id asc"
	UpdateVote                     = "update votes set voice=$1 where author=$2 and thread=$3;"
	InsertVote                     = "insert into votes(author, voice, thread) values ($1, $2, $3);"
	UpdateUser                     = "update users set fullname=coalesce(nullif($1, ''), fullname), about=coalesce(nullif($2, ''), about), email=coalesce(nullif($3, ''), email) where nickname=$4 returning *"
)
